"""Convert the COCO 20k subset to YOLO detection format.

Reads data/coco_subset_20k/annotations/instances_{train,val}2017.json, keeps
only the images actually present in data/coco_subset_20k/images/, and writes
YOLO labels to data/coco_subset_20k/labels/ plus train/val image lists and
dataset yamls (bolo/bolo_coco20k.yaml, and bolo/bolo_tiny.yaml with --tiny).

Usage:
    python -m bolo.prepare_data            # full conversion
    python -m bolo.prepare_data --tiny     # also write the tiny smoke-test split
"""

import argparse
import json
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SUBSET = ROOT / "data" / "coco_subset_20k"
IMG_DIR = SUBSET / "images"
LBL_DIR = SUBSET / "labels"
ANN_DIR = SUBSET / "annotations"

VAL_MOD = 20  # every 20th image (by id) goes to validation (~5%)
TINY_TRAIN = 128
TINY_VAL = 32


def load_coco_index():
    """Index images and annotations from both instances jsons."""
    images = {}
    anns = defaultdict(list)
    cat_ids = None
    for split in ("train", "val"):
        path = ANN_DIR / f"instances_{split}2017.json"
        with open(path) as f:
            d = json.load(f)
        if cat_ids is None:
            cat_ids = sorted(c["id"] for c in d["categories"])
            names = {c["id"]: c["name"] for c in d["categories"]}
        for im in d["images"]:
            images[im["id"]] = (im["file_name"], im["width"], im["height"])
        for a in d["annotations"]:
            if a.get("iscrowd", 0):
                continue
            anns[a["image_id"]].append(a)
    return images, anns, cat_ids, names


def convert(tiny=False):
    images, anns, cat_ids, names = load_coco_index()
    cat_map = {cid: i for i, cid in enumerate(cat_ids)}

    on_disk = {int(p.stem): p for p in IMG_DIR.glob("*.jpg")}
    print(f"images on disk: {len(on_disk)}")

    LBL_DIR.mkdir(exist_ok=True)
    train_list, val_list = [], []
    n_boxes = 0
    for img_id, path in sorted(on_disk.items()):
        if img_id not in images:
            continue
        _, w, h = images[img_id]
        lines = []
        for a in anns.get(img_id, []):
            x, y, bw, bh = a["bbox"]
            if bw <= 0 or bh <= 0:
                continue
            cx, cy = (x + bw / 2) / w, (y + bh / 2) / h
            nw, nh = bw / w, bh / h
            if not (0 <= cx <= 1 and 0 <= cy <= 1 and 0 < nw <= 1 and 0 < nh <= 1):
                continue
            lines.append(f"{cat_map[a['category_id']]} {cx:.6f} {cy:.6f} {nw:.6f} {nh:.6f}")
        (LBL_DIR / f"{path.stem}.txt").write_text("\n".join(lines) + ("\n" if lines else ""))
        n_boxes += len(lines)
        (val_list if img_id % VAL_MOD == 0 else train_list).append(str(path))

    (SUBSET / "train.txt").write_text("\n".join(train_list) + "\n")
    (SUBSET / "val.txt").write_text("\n".join(val_list) + "\n")
    print(f"train: {len(train_list)} images, val: {len(val_list)} images, boxes: {n_boxes}")

    ordered_names = [names[cid] for cid in cat_ids]
    _write_yaml(ROOT / "bolo" / "bolo_coco20k.yaml", SUBSET / "train.txt", SUBSET / "val.txt", ordered_names)

    if tiny:
        (SUBSET / "tiny_train.txt").write_text("\n".join(train_list[:TINY_TRAIN]) + "\n")
        (SUBSET / "tiny_val.txt").write_text("\n".join(val_list[:TINY_VAL]) + "\n")
        _write_yaml(
            ROOT / "bolo" / "bolo_tiny.yaml", SUBSET / "tiny_train.txt", SUBSET / "tiny_val.txt", ordered_names
        )
        print(f"tiny: {TINY_TRAIN} train / {TINY_VAL} val images")


def _write_yaml(path, train_txt, val_txt, names):
    lines = [
        f"# BOLO dataset config (generated by bolo/prepare_data.py)",
        f"train: {train_txt}",
        f"val: {val_txt}",
        f"nc: {len(names)}",
        "names:",
    ]
    lines += [f"  {i}: {n}" for i, n in enumerate(names)]
    path.write_text("\n".join(lines) + "\n")
    print(f"wrote {path}")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--tiny", action="store_true", help="also write the tiny smoke-test split")
    args = ap.parse_args()
    convert(tiny=args.tiny)
